apiVersion: 1

datasources:
  - name: postgres-datasource
    type: postgres
    url: postgresql:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: "superstrongpassword"
    jsonData:
      sslmode: "disable"
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false
