---
- hosts: monitoring
  become: true
  tasks:
    - name: update dependencese
      apt:
        update_cache: yes
        force_apt_get: yes
        name:
          - curl
          - gnupg2
          - ca-certificates
          - lsb-release
          - ubuntu-keyring
          - nginx
          - docker
          - docker-compose
        state: present
    - name: clone repository
      git:
        repo: https://github.com/1kurops/test-tasks.git
        dest: /opt/grafana
        force: yes

    - name: read confd nginx config file
      slurp:
        src: "/opt/grafana/docker/configs/nginx/conf.d/default.conf"
      register: confd_file_content
    - name: copy confd nginx file
      copy:
        content: "{{ confd_file_content['content'] | b64decode }}"
        dest: /etc/nginx/conf.d/default.conf

    - name: read main nginx config file
      slurp:
        src: "/opt/grafana/docker/configs/nginx/nginx.conf"
      register: main_file_content
    - name: copy confd nginx file
      copy:
        content: "{{ main_file_content['content'] | b64decode }}"
        dest: /etc/nginx/nginx.conf

    - name: pull docker images
      shell: docker-compose -f /opt/grafana/docker/docker-compose.yaml pull
    - name: start docker images
      shell: docker-compose -f /opt/grafana/docker/docker-compose.yaml up -d

  handlers:
    - name: Restart nginx with new configuration
      shell: nginx -s reload
